### ISSUE TITLE
Add support for day time format

### ISSUE THREAD

**Issue by alfeugds** [alfeugds/jiraworklogtool#15]
The 'Time Spent' column fields don't accept the day format. e.g.:
`1d`
Change the validator to support it, and add new unit test scenarios to cover the change.

**Comment by felipebcardoso** [comment]
Yes, please! I need day format as Jira

**Comment by alfeugds** [comment]
Fix applied and published in chrome web store. It may take a while to reflect in your browser. Once it is reflected we can close this issue.

**Comment by alfeugds** [comment]
This is completed. Let me know if any issues :)
