### ISSUE TITLE
Cannot connect jira cloud instance

### ISSUE THREAD

**Issue by XanatosX** [alfeugds/jiraworklogtool#16]
## Problem description

I cannot get it to work with my cloud instance, I always get a connection error telling me the URL is not valid.

I'm trying to use this tool because my company is using two different Jira instances with different user accounts ...

The idea was to use this tool to log my time for the second instance while keeping the log-in into the primary instance.

Please give me an advice what could be wrong.

## Information about the options set in the plugin

URL:  https://<Jira URL>/rest/api/2/search
While the Jira URL was set to {instancename}.atlassian.net

Username and password were used.

If I copied the URL to the browser URL I was receiving the JSON data so it seems correct to me.

**Comment by XanatosX** [comment]
Hi @alfeugds 

Thank you for your quick reply.

I already tried to only use the URL but it's still showing a "connection failed" error. If I only enter the **https://{instancename}.atlassian.net** part it shows a "Connection successful" but I think this only checks if the Jira instance is present.

Sadly I did not get one of the Jira instances to a working state, one of them is using a two-factor authentification so I think that could be the problem here but the other should work.

**Comment by alfeugds** [comment]
Hi @XanatosX 

After you entered the **https://{instancename}.atlassian.net** part and received a  "Connection successful" message, if you save the options, you may be able to use the tool and log hours through it.

The tool expects the Jira URL field to be your Jira instance's hostname (I think I should change the label to "Jira Hostname" for clarity). Then, the tool makes the API requests to Jira by joining the hostname with the "/rest/api/2/search" path.

If you use two-factor authentication, you just need to make sure that chrome is logged in to Jira, and let the user/password fields blank.

Let me know if that works for you.

**Comment by XanatosX** [comment]
Hi @alfeugds 

Okay, we got some success, I entered the URL as mentioned by you to my browser logged in to the non two-factor instance. After entering my username and password I finally got a connection. Lucky enough this is the instance I want to connect to.

The next step would be to use this tool in the browser where I'm logged in to the other instance. So I used the same working configuration and switched to the two-factor instance, now the connection error reappears.

So I seem like the cookie is preferred instead of the login?

You should also rewrite the readme.md on the chrome extension shop and on GitHub, if I'm right it tells you to insert the whole API link.

**Comment by alfeugds** [comment]
Hello @XanatosX 

Indeed the login cookie seems to be more stable than the user/password configurations. I intend to make this process more clear by resolving the issue #10 

I'll definitely rewrite both readme.md and the description in Chrome Store, thanks for the tip!

I hope the tool fits your needs, and feel free to reach out if you have any other issues or suggestions.

Since you finally got a connection to the desired Jira instance, do you think we close this issue?

**Comment by XanatosX** [comment]
Hey @alfeugds,

it's not completely working as expected but I can use it which is a big improvement :+1: 

The plan was to be logged in into the two-factor instance but log the time with your tool in the other instance without two-factor authentification. My Idea was to use one browser profile instead of two and write my work log to a note entering it later on with your tool.

But yes I think we can close it and I will start another attempt as soon as #10 is solved :smile: 

Thank you for helping me out and clarifying this up, feel free to close this issue.
