### ISSUE TITLE
Feature request - Add a button to open up the ticket

### ISSUE THREAD

**Issue by XanatosX** [alfeugds/jiraworklogtool#17]
# Feature request

## Description
Rename the "Delete" column to something like actions or create a new one. Add a button next to the delete icon to open the ticket in the browser.

![image](https://user-images.githubusercontent.com/10531466/39703466-6e7302be-5208-11e8-9597-0a39c8e98a0e.png)

## Why would it be helpful
This would allow to check this ticket out after you booked some time on this, this would be helpful to quickly access the ticket description.

**Comment by alfeugds** [comment]
hi @XanatosX 
I've just deployed this feature, please check if it works for you.
Maybe it takes some time to update in the chrome web store and update in your browser, let me know if any issues.

**Comment by XanatosX** [comment]
@alfeugds 
The feature works great thank you for adding this :+1:
