### ISSUE TITLE
Question: Multi line comment

### ISSUE THREAD

**Issue by XanatosX** [alfeugds/jiraworklogtool#20]
Hey @alfeugds,

is it possible to create a multiline comment?
The question is not important everything is working fine.

Yours sincerely,

Simon Aberle

**Comment by alfeugds** [comment]
Hi @XanatosX 
Unfortunately, the extension doesn't support multiline comment today, although Jira seems to support it.
I'll leave this question opened in case someone wants to implement it :)

Regards

**Comment by alfeugds** [comment]
feature request opened: #25 
closing this question for organization purposes.
