### ISSUE TITLE
Parsing time incorrectly when not logging full hour

### ISSUE THREAD

**Issue by quickcoffee** [alfeugds/jiraworklogtool#40]
Hi,
the tool seems to ignore commas or dots when trying to log times other than a full hour (i.e. 3.5h)
![image](https://user-images.githubusercontent.com/31934316/90865153-40cb0a00-e392-11ea-81e7-8308eebd2756.png)

**Comment by alfeugds** [comment]
Hi! Thanks for using the tool and taking the time to report this issue!

The Time Spent field expects you to specify the time in hours and minutes, and it doesn't expect dots, so in your case you would use `3h 30m`. Your worklog in plain text would look like this:
```
IE-234 3h 30m some task
```

I can't remember off the top of my head if Jira supports dots in the time spent value in the website. If it does, I can try to support it too. 
Let me know if that helps :)

**Comment by quickcoffee** [comment]
It seems like my company has a custom function to also parse dots, so probably not worth to support :)
