### ISSUE TITLE
Work log time is fixed to 06:00 AM

### ISSUE THREAD

**Issue by mash1t** [alfeugds/jiraworklogtool#45]
When logging time the work log time is set to 06:00 AM instead of the current timestamp.
Is it possible to change this behavior? 

https://github.com/alfeugds/jiraworklogtool/blob/e097a1aade38294a944b818f2b32d45fc31be4d4/chrome-extension/js/jira-helper.js#L179

Background: sprints normally do start during the day, not at 06:00 AM, which then, when logging time for the day the sprint started, results in logs not showing up in burndown charts.

if yes, what would you (@alfeugds) suggest?
- use current timestamp (recalculated in UTC if necessary) in code directly without any frontend input
- add new field "work log time"
- add checkbox "log for current timestamp"

**Comment by alfeugds** [comment]
Hey @mash1t , first of all thanks for the interest in using it!

Your use case is interesting. I've never needed to worry about the exact time of the worklog, just the date. This is why it's hard-coded. 

We can definitely change it. I like your idea of using the current timestamp and the checkbox.

How urgent is it for you?

**Comment by mash1t** [comment]
Hey @alfeugds, it's not urgent. I already created a fork and adjusted the hardcoded timestamp according to my needs to 6 PM instead of AM, but i'd appreciate it if we could find a solution.

Sadly i'm not that skilled in JavaScript, if i were i would have already created a PR.
It would be great if you or somebody who's developing the Plugin could support here.

**Comment by alfeugds** [comment]
Hey @mash1t , I've fixed the log time by using the browser's local time at 6PM.
The updated chrome extension is already published (0.4.3)
Could you please test it and see if everything looks as expected in your burndown?

**Comment by mash1t** [comment]
@alfeugds works perfectly fine, thank you for the adjustment. Should this issue be kept open as a reminder for the maybe upcoming checkbox "Use current time for work log"?

**Comment by alfeugds** [comment]
I'd say we could close this one since your primary issue is resolved, and if you want the checkbox feature we could open another issue.
